repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: file-contents-sorter
        files: "(\\.gitignore|\\.dockerignore)"
  - repo: local
    hooks:
      - id: cargo-clippy-fix
        name: cargo-clippy-fix
        entry: cargo
        args:
          [
            clippy,
            --fix,
            --allow-dirty,
            --allow-staged,
            --workspace,
            "--",
            "--deny=clippy::correctness",
            "--deny=clippy::pedantic",
            "--deny=clippy::perf",
            "--deny=clippy::style",
            "--deny=clippy::suspicious",
            "--warn=clippy::cargo",
            "--allow=clippy::cast_possible_wrap",
            "--allow=clippy::cast_precision_loss",
            "--allow=clippy::cast_sign_loss",
            "--allow=clippy::missing_errors_doc",
            "--allow=clippy::missing_panics_doc",
            "--allow=clippy::module_name_repetitions",
            "--allow=clippy::similar_names",
            "--allow=clippy::struct_excessive_bools",
            "--allow=clippy::struct_field_names",
          ]
        language: system
        types: [rust]
        pass_filenames: false
        require_serial: true
      - id: cargo-fmt
        name: cargo-fmt
        entry: cargo
        args: [fmt]
        language: system
        types: [rust]
        pass_filenames: false
        require_serial: true
